name: markup_mobile
description: Mark-Up — Platform Pembelajaran & Mentoring
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^1.6.0

  # State Management
  provider: ^6.1.2

  # HTTP Client
  dio: ^5.4.1

  # Local Storage
  shared_preferences: ^2.2.3

  # Google Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/markup.png
    - assets/images/google.png # <-- Tambahkan baris ini
