// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] ?? '',
    appId: dotenv.env['WEB_APP_ID'] ?? '',
    messagingSenderId: '286113394726',
    projectId: 'backend-markup',
    authDomain: 'backend-markup.firebaseapp.com',
    storageBucket: 'backend-markup.firebasestorage.app',
    measurementId: 'G-6ZLXT5B3RZ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['ANDROID_APP_ID'] ?? '',
    messagingSenderId: '286113394726',
    projectId: 'backend-markup',
    storageBucket: 'backend-markup.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? '',
    appId: dotenv.env['IOS_APP_ID'] ?? '',
    messagingSenderId: '286113394726',
    projectId: 'backend-markup',
    storageBucket: 'backend-markup.firebasestorage.app',
    iosBundleId: 'com.example.projectPweb',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY'] ?? '',
    appId: dotenv.env['MACOS_APP_ID'] ?? '',
    messagingSenderId: '286113394726',
    projectId: 'backend-markup',
    storageBucket: 'backend-markup.firebasestorage.app',
    iosBundleId: 'com.example.projectPweb',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_API_KEY'] ?? '',
    appId: dotenv.env['WINDOWS_APP_ID'] ?? '',
    messagingSenderId: '286113394726',
    projectId: 'backend-markup',
    authDomain: 'backend-markup.firebaseapp.com',
    storageBucket: 'backend-markup.firebasestorage.app',
    measurementId: 'G-GQ109QW4EW',
  );
}
